version: '3.10'

services:
  dashboard:
    container_name: dashboard
    build:
      context: .
    command: bash -c "python dashboard/manage.py migrate && python dashboard/manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - main_network
    volumes:
      - db-data:/dashboard
    

  bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - .env
    networks:
      - main_network
    volumes:
      - db-data:/dashboard

volumes:
  db-data:

networks:
  main_network:
    driver: bridge